name: Update
on:
  schedule:
    - cron: "27 4 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update.yml'
  pull_request:
    paths:
      - '.github/workflows/update.yml'

jobs:
  ansible:
    name: Ansible
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Prepare Ansible
        id: prepare_ansible
        uses: LeastAuthority/setup-docker-image@137f365304672bf5ef01a6f3fbb34c5fd848ca15 # v1.0.0
        with:
          service-name: ansible-controller

      - name: Update requirements
        id: update_requirements
        run: |
          docker compose run --rm \
          ansible-controller bash -e << EOC
            # Upgrade the main packages
            pip install --upgrade --upgrade-strategy eager ansible ansible-lint
            # Save the new requirements
            python3 -m pip freeze --local > ../docker/ansible/requirements.txt
            # Reinstall the new requirements to be safe
            pip install --force-reinstall -r ../docker/ansible/requirements.txt
            # Some sanity checks
            python3 -m pip check
            ansible-playbook --version
            ansible-lint --version
          EOC

      - name: Create pull request
        id: create_pr
        if: ${{ contains(fromJSON('["workflow_dispatch", "schedule"]'), github.event_name) }}
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          add-paths: |
            docker/ansible/requirements.txt
          base: "main"
          branch: "update/ansible"
          commit-message: "Update Ansible and its dependencies"
          delete-branch: true
          title: "Update Ansible and its dependencies"
          token: ${{ secrets.GH_PAT_UPDATE }}

  nix:
    name: Nix
    runs-on: nixos
    steps:
      - name: Checkout
        id: checkout
        uses: LeastAuthority/checkout-nix-flake@90a34024508812fd64b012de7c97ff977e32bd46 # v1.0.1

      - name: Update Nix Flake
        id: update_nix_flake
        uses: LeastAuthority/update-nix-flake@6cc50371ca6ca779c40cf7520c1102744d098b9e # v1.0.4
        with:
          branch: "update/nix-flake"
          token: ${{ secrets.GH_PAT_UPDATE }}

  stable:
    name: Stable
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: stable
          fetch-depth: 0

      - name: Changelog
        id: changelog
        run: |
          git log origin/main...HEAD \
            --pretty=format:"* %h (%cd): %s" \
            --date=short \
            --first-parent \
            --left-only \
            --reverse \
            | sed -r -e 's/Merge pull request (#[0-9]+) from .[^ ]+/\1/g' \
            | tee ${{ runner.temp }}/pull-request-body.md \
            >> $GITHUB_STEP_SUMMARY

      - name: Merge
        id: merge
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git merge origin/main

      - name: Create pull request
        id: create_pr
        if: ${{ contains(fromJSON('["workflow_dispatch", "schedule"]'), github.event_name) }}
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          branch: "update/stable"
          commit-message: "Merge main into stable"
          delete-branch: false
          title: "Update stable branch with latest changes"
          token: ${{ secrets.GH_PAT_UPDATE }}
          body-path: "${{ runner.temp }}/pull-request-body.md"
